### ISSUE TITLE
Compatibility with tiptap ?

### ISSUE THREAD

**Issue by ManUtopiK** [marekdedic/prosemirror-unified#170]
[Tiptap](https://tiptap.dev) use prosemirror under the hood.
I tried to use your lib with tiptap. It seems that the output of `pmu.parse(sourceMarkdown)` differ from the `editor.getJSON()` of a tiptap instance. Do you know if this library is compatible with tiptap ?

**Comment by marekdedic** [comment]
Hi, I have honestly never heard about it, will investigate.

**Comment by marekdedic** [comment]
Hi,
looking at it a little bit, it seems there's no simple way of making it work. Tiptap seems to be built on top of ProseMirror, but configures it with its own node types (text, image, bold...), prosemirror-unified and prosemirror-remark largely do the same thing. If you want to use markdown, I'd advise running prosemirror with prosemirror-remark directly, without tiptap.

**Comment by ManUtopiK** [comment]
Thank you for your investigations and suggestions !
